/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package lol.memory.ts.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;

@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase
        implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 7941545529093403492L;

    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
            "{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"lol.memory.ts.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"screen_name\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"location\",\"type\":[\"null\",\"string\"]},{\"name\":\"url\",\"type\":[\"null\",\"string\"]},{\"name\":\"description\",\"type\":[\"null\",\"string\"]},{\"name\":\"protected\",\"type\":\"boolean\",\"default\":false},{\"name\":\"verified\",\"type\":\"boolean\",\"default\":false},{\"name\":\"followers_count\",\"type\":\"long\"},{\"name\":\"friends_count\",\"type\":\"long\"},{\"name\":\"listed_count\",\"type\":\"long\"},{\"name\":\"favourites_count\",\"type\":\"long\"},{\"name\":\"statuses_count\",\"type\":\"long\"},{\"name\":\"created_at\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"profile_image_url\",\"type\":\"string\"},{\"name\":\"profile_banner_url\",\"type\":[\"null\",\"string\"]},{\"name\":\"profile_background_image_url\",\"type\":[\"null\",\"string\"]},{\"name\":\"default_profile\",\"type\":\"boolean\"},{\"name\":\"default_profile_image\",\"type\":\"boolean\"},{\"name\":\"withheld_in_countries\",\"type\":{\"type\":\"array\",\"items\":\"string\",\"default\":[]}},{\"name\":\"time_zone\",\"type\":[\"null\",\"string\"]},{\"name\":\"lang\",\"type\":[\"null\",\"string\"]},{\"name\":\"geo_enabled\",\"type\":[\"null\",\"boolean\"]}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();
    static {
        MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    }

    private static final BinaryMessageEncoder<User> ENCODER = new BinaryMessageEncoder<User>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<User> DECODER = new BinaryMessageDecoder<User>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * 
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<User> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * 
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<User> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * 
     * @param resolver
     *            a {@link SchemaStore} used to find schemas by fingerprint
     * 
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<User> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<User>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this User to a ByteBuffer.
     * 
     * @return a buffer holding the serialized data for this instance
     * 
     * @throws java.io.IOException
     *             if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a User from a ByteBuffer.
     * 
     * @param b
     *            a byte buffer holding serialized data for an instance of this class
     * 
     * @return a User instance decoded from the given buffer
     * 
     * @throws java.io.IOException
     *             if the given bytes could not be deserialized into an instance of this class
     */
    public static User fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private long id;
    private java.time.Instant timestamp;
    private java.lang.CharSequence screen_name;
    private java.lang.CharSequence name;
    private java.lang.CharSequence location;
    private java.lang.CharSequence url;
    private java.lang.CharSequence description;
    private boolean protected$;
    private boolean verified;
    private long followers_count;
    private long friends_count;
    private long listed_count;
    private long favourites_count;
    private long statuses_count;
    private java.time.Instant created_at;
    private java.lang.CharSequence profile_image_url;
    private java.lang.CharSequence profile_banner_url;
    private java.lang.CharSequence profile_background_image_url;
    private boolean default_profile;
    private boolean default_profile_image;
    private java.util.List<java.lang.CharSequence> withheld_in_countries;
    private java.lang.CharSequence time_zone;
    private java.lang.CharSequence lang;
    private java.lang.Boolean geo_enabled;

    /**
     * Default constructor. Note that this does not initialize fields to their default values from the schema. If that
     * is desired then one should use <code>newBuilder()</code>.
     */
    public User() {
    }

    /**
     * All-args constructor.
     * 
     * @param id
     *            The new value for id
     * @param timestamp
     *            The new value for timestamp
     * @param screen_name
     *            The new value for screen_name
     * @param name
     *            The new value for name
     * @param location
     *            The new value for location
     * @param url
     *            The new value for url
     * @param description
     *            The new value for description
     * @param protected$
     *            The new value for protected
     * @param verified
     *            The new value for verified
     * @param followers_count
     *            The new value for followers_count
     * @param friends_count
     *            The new value for friends_count
     * @param listed_count
     *            The new value for listed_count
     * @param favourites_count
     *            The new value for favourites_count
     * @param statuses_count
     *            The new value for statuses_count
     * @param created_at
     *            The new value for created_at
     * @param profile_image_url
     *            The new value for profile_image_url
     * @param profile_banner_url
     *            The new value for profile_banner_url
     * @param profile_background_image_url
     *            The new value for profile_background_image_url
     * @param default_profile
     *            The new value for default_profile
     * @param default_profile_image
     *            The new value for default_profile_image
     * @param withheld_in_countries
     *            The new value for withheld_in_countries
     * @param time_zone
     *            The new value for time_zone
     * @param lang
     *            The new value for lang
     * @param geo_enabled
     *            The new value for geo_enabled
     */
    public User(java.lang.Long id, java.time.Instant timestamp, java.lang.CharSequence screen_name,
            java.lang.CharSequence name, java.lang.CharSequence location, java.lang.CharSequence url,
            java.lang.CharSequence description, java.lang.Boolean protected$, java.lang.Boolean verified,
            java.lang.Long followers_count, java.lang.Long friends_count, java.lang.Long listed_count,
            java.lang.Long favourites_count, java.lang.Long statuses_count, java.time.Instant created_at,
            java.lang.CharSequence profile_image_url, java.lang.CharSequence profile_banner_url,
            java.lang.CharSequence profile_background_image_url, java.lang.Boolean default_profile,
            java.lang.Boolean default_profile_image, java.util.List<java.lang.CharSequence> withheld_in_countries,
            java.lang.CharSequence time_zone, java.lang.CharSequence lang, java.lang.Boolean geo_enabled) {
        this.id = id;
        this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
        this.screen_name = screen_name;
        this.name = name;
        this.location = location;
        this.url = url;
        this.description = description;
        this.protected$ = protected$;
        this.verified = verified;
        this.followers_count = followers_count;
        this.friends_count = friends_count;
        this.listed_count = listed_count;
        this.favourites_count = favourites_count;
        this.statuses_count = statuses_count;
        this.created_at = created_at.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
        this.profile_image_url = profile_image_url;
        this.profile_banner_url = profile_banner_url;
        this.profile_background_image_url = profile_background_image_url;
        this.default_profile = default_profile;
        this.default_profile_image = default_profile_image;
        this.withheld_in_countries = withheld_in_countries;
        this.time_zone = time_zone;
        this.lang = lang;
        this.geo_enabled = geo_enabled;
    }

    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter. Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
        case 0:
            return id;
        case 1:
            return timestamp;
        case 2:
            return screen_name;
        case 3:
            return name;
        case 4:
            return location;
        case 5:
            return url;
        case 6:
            return description;
        case 7:
            return protected$;
        case 8:
            return verified;
        case 9:
            return followers_count;
        case 10:
            return friends_count;
        case 11:
            return listed_count;
        case 12:
            return favourites_count;
        case 13:
            return statuses_count;
        case 14:
            return created_at;
        case 15:
            return profile_image_url;
        case 16:
            return profile_banner_url;
        case 17:
            return profile_background_image_url;
        case 18:
            return default_profile;
        case 19:
            return default_profile_image;
        case 20:
            return withheld_in_countries;
        case 21:
            return time_zone;
        case 22:
            return lang;
        case 23:
            return geo_enabled;
        default:
            throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    private static final org.apache.avro.Conversion<?>[] conversions = new org.apache.avro.Conversion<?>[] { null,
            new org.apache.avro.data.TimeConversions.TimestampMillisConversion(), null, null, null, null, null, null,
            null, null, null, null, null, null, new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
            null, null, null, null, null, null, null, null, null, null };

    @Override
    public org.apache.avro.Conversion<?> getConversion(int field) {
        return conversions[field];
    }

    // Used by DatumReader. Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
        case 0:
            id = (java.lang.Long) value$;
            break;
        case 1:
            timestamp = (java.time.Instant) value$;
            break;
        case 2:
            screen_name = (java.lang.CharSequence) value$;
            break;
        case 3:
            name = (java.lang.CharSequence) value$;
            break;
        case 4:
            location = (java.lang.CharSequence) value$;
            break;
        case 5:
            url = (java.lang.CharSequence) value$;
            break;
        case 6:
            description = (java.lang.CharSequence) value$;
            break;
        case 7:
            protected$ = (java.lang.Boolean) value$;
            break;
        case 8:
            verified = (java.lang.Boolean) value$;
            break;
        case 9:
            followers_count = (java.lang.Long) value$;
            break;
        case 10:
            friends_count = (java.lang.Long) value$;
            break;
        case 11:
            listed_count = (java.lang.Long) value$;
            break;
        case 12:
            favourites_count = (java.lang.Long) value$;
            break;
        case 13:
            statuses_count = (java.lang.Long) value$;
            break;
        case 14:
            created_at = (java.time.Instant) value$;
            break;
        case 15:
            profile_image_url = (java.lang.CharSequence) value$;
            break;
        case 16:
            profile_banner_url = (java.lang.CharSequence) value$;
            break;
        case 17:
            profile_background_image_url = (java.lang.CharSequence) value$;
            break;
        case 18:
            default_profile = (java.lang.Boolean) value$;
            break;
        case 19:
            default_profile_image = (java.lang.Boolean) value$;
            break;
        case 20:
            withheld_in_countries = (java.util.List<java.lang.CharSequence>) value$;
            break;
        case 21:
            time_zone = (java.lang.CharSequence) value$;
            break;
        case 22:
            lang = (java.lang.CharSequence) value$;
            break;
        case 23:
            geo_enabled = (java.lang.Boolean) value$;
            break;
        default:
            throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'id' field.
     * 
     * @return The value of the 'id' field.
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the 'id' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the 'timestamp' field.
     * 
     * @return The value of the 'timestamp' field.
     */
    public java.time.Instant getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the 'timestamp' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setTimestamp(java.time.Instant value) {
        this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    }

    /**
     * Gets the value of the 'screen_name' field.
     * 
     * @return The value of the 'screen_name' field.
     */
    public java.lang.CharSequence getScreenName() {
        return screen_name;
    }

    /**
     * Sets the value of the 'screen_name' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setScreenName(java.lang.CharSequence value) {
        this.screen_name = value;
    }

    /**
     * Gets the value of the 'name' field.
     * 
     * @return The value of the 'name' field.
     */
    public java.lang.CharSequence getName() {
        return name;
    }

    /**
     * Sets the value of the 'name' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setName(java.lang.CharSequence value) {
        this.name = value;
    }

    /**
     * Gets the value of the 'location' field as an Optional&lt;java.lang.CharSequence&gt;.
     * 
     * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
     */
    public Optional<java.lang.CharSequence> getLocation() {
        return Optional.<java.lang.CharSequence> ofNullable(location);
    }

    /**
     * Sets the value of the 'location' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setLocation(java.lang.CharSequence value) {
        this.location = value;
    }

    /**
     * Gets the value of the 'url' field as an Optional&lt;java.lang.CharSequence&gt;.
     * 
     * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
     */
    public Optional<java.lang.CharSequence> getUrl() {
        return Optional.<java.lang.CharSequence> ofNullable(url);
    }

    /**
     * Sets the value of the 'url' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setUrl(java.lang.CharSequence value) {
        this.url = value;
    }

    /**
     * Gets the value of the 'description' field as an Optional&lt;java.lang.CharSequence&gt;.
     * 
     * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
     */
    public Optional<java.lang.CharSequence> getDescription() {
        return Optional.<java.lang.CharSequence> ofNullable(description);
    }

    /**
     * Sets the value of the 'description' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setDescription(java.lang.CharSequence value) {
        this.description = value;
    }

    /**
     * Gets the value of the 'protected$' field.
     * 
     * @return The value of the 'protected$' field.
     */
    public boolean getProtected$() {
        return protected$;
    }

    /**
     * Sets the value of the 'protected$' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setProtected$(boolean value) {
        this.protected$ = value;
    }

    /**
     * Gets the value of the 'verified' field.
     * 
     * @return The value of the 'verified' field.
     */
    public boolean getVerified() {
        return verified;
    }

    /**
     * Sets the value of the 'verified' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setVerified(boolean value) {
        this.verified = value;
    }

    /**
     * Gets the value of the 'followers_count' field.
     * 
     * @return The value of the 'followers_count' field.
     */
    public long getFollowersCount() {
        return followers_count;
    }

    /**
     * Sets the value of the 'followers_count' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setFollowersCount(long value) {
        this.followers_count = value;
    }

    /**
     * Gets the value of the 'friends_count' field.
     * 
     * @return The value of the 'friends_count' field.
     */
    public long getFriendsCount() {
        return friends_count;
    }

    /**
     * Sets the value of the 'friends_count' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setFriendsCount(long value) {
        this.friends_count = value;
    }

    /**
     * Gets the value of the 'listed_count' field.
     * 
     * @return The value of the 'listed_count' field.
     */
    public long getListedCount() {
        return listed_count;
    }

    /**
     * Sets the value of the 'listed_count' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setListedCount(long value) {
        this.listed_count = value;
    }

    /**
     * Gets the value of the 'favourites_count' field.
     * 
     * @return The value of the 'favourites_count' field.
     */
    public long getFavouritesCount() {
        return favourites_count;
    }

    /**
     * Sets the value of the 'favourites_count' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setFavouritesCount(long value) {
        this.favourites_count = value;
    }

    /**
     * Gets the value of the 'statuses_count' field.
     * 
     * @return The value of the 'statuses_count' field.
     */
    public long getStatusesCount() {
        return statuses_count;
    }

    /**
     * Sets the value of the 'statuses_count' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setStatusesCount(long value) {
        this.statuses_count = value;
    }

    /**
     * Gets the value of the 'created_at' field.
     * 
     * @return The value of the 'created_at' field.
     */
    public java.time.Instant getCreatedAt() {
        return created_at;
    }

    /**
     * Sets the value of the 'created_at' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setCreatedAt(java.time.Instant value) {
        this.created_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    }

    /**
     * Gets the value of the 'profile_image_url' field.
     * 
     * @return The value of the 'profile_image_url' field.
     */
    public java.lang.CharSequence getProfileImageUrl() {
        return profile_image_url;
    }

    /**
     * Sets the value of the 'profile_image_url' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setProfileImageUrl(java.lang.CharSequence value) {
        this.profile_image_url = value;
    }

    /**
     * Gets the value of the 'profile_banner_url' field as an Optional&lt;java.lang.CharSequence&gt;.
     * 
     * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
     */
    public Optional<java.lang.CharSequence> getProfileBannerUrl() {
        return Optional.<java.lang.CharSequence> ofNullable(profile_banner_url);
    }

    /**
     * Sets the value of the 'profile_banner_url' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setProfileBannerUrl(java.lang.CharSequence value) {
        this.profile_banner_url = value;
    }

    /**
     * Gets the value of the 'profile_background_image_url' field as an Optional&lt;java.lang.CharSequence&gt;.
     * 
     * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
     */
    public Optional<java.lang.CharSequence> getProfileBackgroundImageUrl() {
        return Optional.<java.lang.CharSequence> ofNullable(profile_background_image_url);
    }

    /**
     * Sets the value of the 'profile_background_image_url' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setProfileBackgroundImageUrl(java.lang.CharSequence value) {
        this.profile_background_image_url = value;
    }

    /**
     * Gets the value of the 'default_profile' field.
     * 
     * @return The value of the 'default_profile' field.
     */
    public boolean getDefaultProfile() {
        return default_profile;
    }

    /**
     * Sets the value of the 'default_profile' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setDefaultProfile(boolean value) {
        this.default_profile = value;
    }

    /**
     * Gets the value of the 'default_profile_image' field.
     * 
     * @return The value of the 'default_profile_image' field.
     */
    public boolean getDefaultProfileImage() {
        return default_profile_image;
    }

    /**
     * Sets the value of the 'default_profile_image' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setDefaultProfileImage(boolean value) {
        this.default_profile_image = value;
    }

    /**
     * Gets the value of the 'withheld_in_countries' field.
     * 
     * @return The value of the 'withheld_in_countries' field.
     */
    public java.util.List<java.lang.CharSequence> getWithheldInCountries() {
        return withheld_in_countries;
    }

    /**
     * Sets the value of the 'withheld_in_countries' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setWithheldInCountries(java.util.List<java.lang.CharSequence> value) {
        this.withheld_in_countries = value;
    }

    /**
     * Gets the value of the 'time_zone' field as an Optional&lt;java.lang.CharSequence&gt;.
     * 
     * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
     */
    public Optional<java.lang.CharSequence> getTimeZone() {
        return Optional.<java.lang.CharSequence> ofNullable(time_zone);
    }

    /**
     * Sets the value of the 'time_zone' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setTimeZone(java.lang.CharSequence value) {
        this.time_zone = value;
    }

    /**
     * Gets the value of the 'lang' field as an Optional&lt;java.lang.CharSequence&gt;.
     * 
     * @return The value wrapped in an Optional&lt;java.lang.CharSequence&gt;.
     */
    public Optional<java.lang.CharSequence> getLang() {
        return Optional.<java.lang.CharSequence> ofNullable(lang);
    }

    /**
     * Sets the value of the 'lang' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setLang(java.lang.CharSequence value) {
        this.lang = value;
    }

    /**
     * Gets the value of the 'geo_enabled' field as an Optional&lt;java.lang.Boolean&gt;.
     * 
     * @return The value wrapped in an Optional&lt;java.lang.Boolean&gt;.
     */
    public Optional<java.lang.Boolean> getGeoEnabled() {
        return Optional.<java.lang.Boolean> ofNullable(geo_enabled);
    }

    /**
     * Sets the value of the 'geo_enabled' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setGeoEnabled(java.lang.Boolean value) {
        this.geo_enabled = value;
    }

    /**
     * Creates a new User RecordBuilder.
     * 
     * @return A new User RecordBuilder
     */
    public static lol.memory.ts.avro.User.Builder newBuilder() {
        return new lol.memory.ts.avro.User.Builder();
    }

    /**
     * Creates a new User RecordBuilder by copying an existing Builder.
     * 
     * @param other
     *            The existing builder to copy.
     * 
     * @return A new User RecordBuilder
     */
    public static lol.memory.ts.avro.User.Builder newBuilder(lol.memory.ts.avro.User.Builder other) {
        if (other == null) {
            return new lol.memory.ts.avro.User.Builder();
        } else {
            return new lol.memory.ts.avro.User.Builder(other);
        }
    }

    /**
     * Creates a new User RecordBuilder by copying an existing User instance.
     * 
     * @param other
     *            The existing instance to copy.
     * 
     * @return A new User RecordBuilder
     */
    public static lol.memory.ts.avro.User.Builder newBuilder(lol.memory.ts.avro.User other) {
        if (other == null) {
            return new lol.memory.ts.avro.User.Builder();
        } else {
            return new lol.memory.ts.avro.User.Builder(other);
        }
    }

    /**
     * RecordBuilder for User instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
            implements org.apache.avro.data.RecordBuilder<User> {

        private long id;
        private java.time.Instant timestamp;
        private java.lang.CharSequence screen_name;
        private java.lang.CharSequence name;
        private java.lang.CharSequence location;
        private java.lang.CharSequence url;
        private java.lang.CharSequence description;
        private boolean protected$;
        private boolean verified;
        private long followers_count;
        private long friends_count;
        private long listed_count;
        private long favourites_count;
        private long statuses_count;
        private java.time.Instant created_at;
        private java.lang.CharSequence profile_image_url;
        private java.lang.CharSequence profile_banner_url;
        private java.lang.CharSequence profile_background_image_url;
        private boolean default_profile;
        private boolean default_profile_image;
        private java.util.List<java.lang.CharSequence> withheld_in_countries;
        private java.lang.CharSequence time_zone;
        private java.lang.CharSequence lang;
        private java.lang.Boolean geo_enabled;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * 
         * @param other
         *            The existing Builder to copy.
         */
        private Builder(lol.memory.ts.avro.User.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.timestamp)) {
                this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.screen_name)) {
                this.screen_name = data().deepCopy(fields()[2].schema(), other.screen_name);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.name)) {
                this.name = data().deepCopy(fields()[3].schema(), other.name);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
            if (isValidValue(fields()[4], other.location)) {
                this.location = data().deepCopy(fields()[4].schema(), other.location);
                fieldSetFlags()[4] = other.fieldSetFlags()[4];
            }
            if (isValidValue(fields()[5], other.url)) {
                this.url = data().deepCopy(fields()[5].schema(), other.url);
                fieldSetFlags()[5] = other.fieldSetFlags()[5];
            }
            if (isValidValue(fields()[6], other.description)) {
                this.description = data().deepCopy(fields()[6].schema(), other.description);
                fieldSetFlags()[6] = other.fieldSetFlags()[6];
            }
            if (isValidValue(fields()[7], other.protected$)) {
                this.protected$ = data().deepCopy(fields()[7].schema(), other.protected$);
                fieldSetFlags()[7] = other.fieldSetFlags()[7];
            }
            if (isValidValue(fields()[8], other.verified)) {
                this.verified = data().deepCopy(fields()[8].schema(), other.verified);
                fieldSetFlags()[8] = other.fieldSetFlags()[8];
            }
            if (isValidValue(fields()[9], other.followers_count)) {
                this.followers_count = data().deepCopy(fields()[9].schema(), other.followers_count);
                fieldSetFlags()[9] = other.fieldSetFlags()[9];
            }
            if (isValidValue(fields()[10], other.friends_count)) {
                this.friends_count = data().deepCopy(fields()[10].schema(), other.friends_count);
                fieldSetFlags()[10] = other.fieldSetFlags()[10];
            }
            if (isValidValue(fields()[11], other.listed_count)) {
                this.listed_count = data().deepCopy(fields()[11].schema(), other.listed_count);
                fieldSetFlags()[11] = other.fieldSetFlags()[11];
            }
            if (isValidValue(fields()[12], other.favourites_count)) {
                this.favourites_count = data().deepCopy(fields()[12].schema(), other.favourites_count);
                fieldSetFlags()[12] = other.fieldSetFlags()[12];
            }
            if (isValidValue(fields()[13], other.statuses_count)) {
                this.statuses_count = data().deepCopy(fields()[13].schema(), other.statuses_count);
                fieldSetFlags()[13] = other.fieldSetFlags()[13];
            }
            if (isValidValue(fields()[14], other.created_at)) {
                this.created_at = data().deepCopy(fields()[14].schema(), other.created_at);
                fieldSetFlags()[14] = other.fieldSetFlags()[14];
            }
            if (isValidValue(fields()[15], other.profile_image_url)) {
                this.profile_image_url = data().deepCopy(fields()[15].schema(), other.profile_image_url);
                fieldSetFlags()[15] = other.fieldSetFlags()[15];
            }
            if (isValidValue(fields()[16], other.profile_banner_url)) {
                this.profile_banner_url = data().deepCopy(fields()[16].schema(), other.profile_banner_url);
                fieldSetFlags()[16] = other.fieldSetFlags()[16];
            }
            if (isValidValue(fields()[17], other.profile_background_image_url)) {
                this.profile_background_image_url = data().deepCopy(fields()[17].schema(),
                        other.profile_background_image_url);
                fieldSetFlags()[17] = other.fieldSetFlags()[17];
            }
            if (isValidValue(fields()[18], other.default_profile)) {
                this.default_profile = data().deepCopy(fields()[18].schema(), other.default_profile);
                fieldSetFlags()[18] = other.fieldSetFlags()[18];
            }
            if (isValidValue(fields()[19], other.default_profile_image)) {
                this.default_profile_image = data().deepCopy(fields()[19].schema(), other.default_profile_image);
                fieldSetFlags()[19] = other.fieldSetFlags()[19];
            }
            if (isValidValue(fields()[20], other.withheld_in_countries)) {
                this.withheld_in_countries = data().deepCopy(fields()[20].schema(), other.withheld_in_countries);
                fieldSetFlags()[20] = other.fieldSetFlags()[20];
            }
            if (isValidValue(fields()[21], other.time_zone)) {
                this.time_zone = data().deepCopy(fields()[21].schema(), other.time_zone);
                fieldSetFlags()[21] = other.fieldSetFlags()[21];
            }
            if (isValidValue(fields()[22], other.lang)) {
                this.lang = data().deepCopy(fields()[22].schema(), other.lang);
                fieldSetFlags()[22] = other.fieldSetFlags()[22];
            }
            if (isValidValue(fields()[23], other.geo_enabled)) {
                this.geo_enabled = data().deepCopy(fields()[23].schema(), other.geo_enabled);
                fieldSetFlags()[23] = other.fieldSetFlags()[23];
            }
        }

        /**
         * Creates a Builder by copying an existing User instance
         * 
         * @param other
         *            The existing instance to copy.
         */
        private Builder(lol.memory.ts.avro.User other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.timestamp)) {
                this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.screen_name)) {
                this.screen_name = data().deepCopy(fields()[2].schema(), other.screen_name);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.name)) {
                this.name = data().deepCopy(fields()[3].schema(), other.name);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.location)) {
                this.location = data().deepCopy(fields()[4].schema(), other.location);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.url)) {
                this.url = data().deepCopy(fields()[5].schema(), other.url);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.description)) {
                this.description = data().deepCopy(fields()[6].schema(), other.description);
                fieldSetFlags()[6] = true;
            }
            if (isValidValue(fields()[7], other.protected$)) {
                this.protected$ = data().deepCopy(fields()[7].schema(), other.protected$);
                fieldSetFlags()[7] = true;
            }
            if (isValidValue(fields()[8], other.verified)) {
                this.verified = data().deepCopy(fields()[8].schema(), other.verified);
                fieldSetFlags()[8] = true;
            }
            if (isValidValue(fields()[9], other.followers_count)) {
                this.followers_count = data().deepCopy(fields()[9].schema(), other.followers_count);
                fieldSetFlags()[9] = true;
            }
            if (isValidValue(fields()[10], other.friends_count)) {
                this.friends_count = data().deepCopy(fields()[10].schema(), other.friends_count);
                fieldSetFlags()[10] = true;
            }
            if (isValidValue(fields()[11], other.listed_count)) {
                this.listed_count = data().deepCopy(fields()[11].schema(), other.listed_count);
                fieldSetFlags()[11] = true;
            }
            if (isValidValue(fields()[12], other.favourites_count)) {
                this.favourites_count = data().deepCopy(fields()[12].schema(), other.favourites_count);
                fieldSetFlags()[12] = true;
            }
            if (isValidValue(fields()[13], other.statuses_count)) {
                this.statuses_count = data().deepCopy(fields()[13].schema(), other.statuses_count);
                fieldSetFlags()[13] = true;
            }
            if (isValidValue(fields()[14], other.created_at)) {
                this.created_at = data().deepCopy(fields()[14].schema(), other.created_at);
                fieldSetFlags()[14] = true;
            }
            if (isValidValue(fields()[15], other.profile_image_url)) {
                this.profile_image_url = data().deepCopy(fields()[15].schema(), other.profile_image_url);
                fieldSetFlags()[15] = true;
            }
            if (isValidValue(fields()[16], other.profile_banner_url)) {
                this.profile_banner_url = data().deepCopy(fields()[16].schema(), other.profile_banner_url);
                fieldSetFlags()[16] = true;
            }
            if (isValidValue(fields()[17], other.profile_background_image_url)) {
                this.profile_background_image_url = data().deepCopy(fields()[17].schema(),
                        other.profile_background_image_url);
                fieldSetFlags()[17] = true;
            }
            if (isValidValue(fields()[18], other.default_profile)) {
                this.default_profile = data().deepCopy(fields()[18].schema(), other.default_profile);
                fieldSetFlags()[18] = true;
            }
            if (isValidValue(fields()[19], other.default_profile_image)) {
                this.default_profile_image = data().deepCopy(fields()[19].schema(), other.default_profile_image);
                fieldSetFlags()[19] = true;
            }
            if (isValidValue(fields()[20], other.withheld_in_countries)) {
                this.withheld_in_countries = data().deepCopy(fields()[20].schema(), other.withheld_in_countries);
                fieldSetFlags()[20] = true;
            }
            if (isValidValue(fields()[21], other.time_zone)) {
                this.time_zone = data().deepCopy(fields()[21].schema(), other.time_zone);
                fieldSetFlags()[21] = true;
            }
            if (isValidValue(fields()[22], other.lang)) {
                this.lang = data().deepCopy(fields()[22].schema(), other.lang);
                fieldSetFlags()[22] = true;
            }
            if (isValidValue(fields()[23], other.geo_enabled)) {
                this.geo_enabled = data().deepCopy(fields()[23].schema(), other.geo_enabled);
                fieldSetFlags()[23] = true;
            }
        }

        /**
         * Gets the value of the 'id' field.
         * 
         * @return The value.
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the 'id' field.
         * 
         * @param value
         *            The value of 'id'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setId(long value) {
            validate(fields()[0], value);
            this.id = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'id' field has been set.
         * 
         * @return True if the 'id' field has been set, false otherwise.
         */
        public boolean hasId() {
            return fieldSetFlags()[0];
        }

        /**
         * Clears the value of the 'id' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearId() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'timestamp' field.
         * 
         * @return The value.
         */
        public java.time.Instant getTimestamp() {
            return timestamp;
        }

        /**
         * Sets the value of the 'timestamp' field.
         * 
         * @param value
         *            The value of 'timestamp'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setTimestamp(java.time.Instant value) {
            validate(fields()[1], value);
            this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'timestamp' field has been set.
         * 
         * @return True if the 'timestamp' field has been set, false otherwise.
         */
        public boolean hasTimestamp() {
            return fieldSetFlags()[1];
        }

        /**
         * Clears the value of the 'timestamp' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearTimestamp() {
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'screen_name' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getScreenName() {
            return screen_name;
        }

        /**
         * Sets the value of the 'screen_name' field.
         * 
         * @param value
         *            The value of 'screen_name'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setScreenName(java.lang.CharSequence value) {
            validate(fields()[2], value);
            this.screen_name = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'screen_name' field has been set.
         * 
         * @return True if the 'screen_name' field has been set, false otherwise.
         */
        public boolean hasScreenName() {
            return fieldSetFlags()[2];
        }

        /**
         * Clears the value of the 'screen_name' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearScreenName() {
            screen_name = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'name' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getName() {
            return name;
        }

        /**
         * Sets the value of the 'name' field.
         * 
         * @param value
         *            The value of 'name'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setName(java.lang.CharSequence value) {
            validate(fields()[3], value);
            this.name = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'name' field has been set.
         * 
         * @return True if the 'name' field has been set, false otherwise.
         */
        public boolean hasName() {
            return fieldSetFlags()[3];
        }

        /**
         * Clears the value of the 'name' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearName() {
            name = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'location' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getLocation() {
            return location;
        }

        /**
         * Sets the value of the 'location' field.
         * 
         * @param value
         *            The value of 'location'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setLocation(java.lang.CharSequence value) {
            validate(fields()[4], value);
            this.location = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'location' field has been set.
         * 
         * @return True if the 'location' field has been set, false otherwise.
         */
        public boolean hasLocation() {
            return fieldSetFlags()[4];
        }

        /**
         * Clears the value of the 'location' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearLocation() {
            location = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        /**
         * Gets the value of the 'url' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getUrl() {
            return url;
        }

        /**
         * Sets the value of the 'url' field.
         * 
         * @param value
         *            The value of 'url'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setUrl(java.lang.CharSequence value) {
            validate(fields()[5], value);
            this.url = value;
            fieldSetFlags()[5] = true;
            return this;
        }

        /**
         * Checks whether the 'url' field has been set.
         * 
         * @return True if the 'url' field has been set, false otherwise.
         */
        public boolean hasUrl() {
            return fieldSetFlags()[5];
        }

        /**
         * Clears the value of the 'url' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearUrl() {
            url = null;
            fieldSetFlags()[5] = false;
            return this;
        }

        /**
         * Gets the value of the 'description' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getDescription() {
            return description;
        }

        /**
         * Sets the value of the 'description' field.
         * 
         * @param value
         *            The value of 'description'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setDescription(java.lang.CharSequence value) {
            validate(fields()[6], value);
            this.description = value;
            fieldSetFlags()[6] = true;
            return this;
        }

        /**
         * Checks whether the 'description' field has been set.
         * 
         * @return True if the 'description' field has been set, false otherwise.
         */
        public boolean hasDescription() {
            return fieldSetFlags()[6];
        }

        /**
         * Clears the value of the 'description' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearDescription() {
            description = null;
            fieldSetFlags()[6] = false;
            return this;
        }

        /**
         * Gets the value of the 'protected$' field.
         * 
         * @return The value.
         */
        public boolean getProtected$() {
            return protected$;
        }

        /**
         * Sets the value of the 'protected$' field.
         * 
         * @param value
         *            The value of 'protected$'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setProtected$(boolean value) {
            validate(fields()[7], value);
            this.protected$ = value;
            fieldSetFlags()[7] = true;
            return this;
        }

        /**
         * Checks whether the 'protected$' field has been set.
         * 
         * @return True if the 'protected$' field has been set, false otherwise.
         */
        public boolean hasProtected$() {
            return fieldSetFlags()[7];
        }

        /**
         * Clears the value of the 'protected$' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearProtected$() {
            fieldSetFlags()[7] = false;
            return this;
        }

        /**
         * Gets the value of the 'verified' field.
         * 
         * @return The value.
         */
        public boolean getVerified() {
            return verified;
        }

        /**
         * Sets the value of the 'verified' field.
         * 
         * @param value
         *            The value of 'verified'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setVerified(boolean value) {
            validate(fields()[8], value);
            this.verified = value;
            fieldSetFlags()[8] = true;
            return this;
        }

        /**
         * Checks whether the 'verified' field has been set.
         * 
         * @return True if the 'verified' field has been set, false otherwise.
         */
        public boolean hasVerified() {
            return fieldSetFlags()[8];
        }

        /**
         * Clears the value of the 'verified' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearVerified() {
            fieldSetFlags()[8] = false;
            return this;
        }

        /**
         * Gets the value of the 'followers_count' field.
         * 
         * @return The value.
         */
        public long getFollowersCount() {
            return followers_count;
        }

        /**
         * Sets the value of the 'followers_count' field.
         * 
         * @param value
         *            The value of 'followers_count'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setFollowersCount(long value) {
            validate(fields()[9], value);
            this.followers_count = value;
            fieldSetFlags()[9] = true;
            return this;
        }

        /**
         * Checks whether the 'followers_count' field has been set.
         * 
         * @return True if the 'followers_count' field has been set, false otherwise.
         */
        public boolean hasFollowersCount() {
            return fieldSetFlags()[9];
        }

        /**
         * Clears the value of the 'followers_count' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearFollowersCount() {
            fieldSetFlags()[9] = false;
            return this;
        }

        /**
         * Gets the value of the 'friends_count' field.
         * 
         * @return The value.
         */
        public long getFriendsCount() {
            return friends_count;
        }

        /**
         * Sets the value of the 'friends_count' field.
         * 
         * @param value
         *            The value of 'friends_count'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setFriendsCount(long value) {
            validate(fields()[10], value);
            this.friends_count = value;
            fieldSetFlags()[10] = true;
            return this;
        }

        /**
         * Checks whether the 'friends_count' field has been set.
         * 
         * @return True if the 'friends_count' field has been set, false otherwise.
         */
        public boolean hasFriendsCount() {
            return fieldSetFlags()[10];
        }

        /**
         * Clears the value of the 'friends_count' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearFriendsCount() {
            fieldSetFlags()[10] = false;
            return this;
        }

        /**
         * Gets the value of the 'listed_count' field.
         * 
         * @return The value.
         */
        public long getListedCount() {
            return listed_count;
        }

        /**
         * Sets the value of the 'listed_count' field.
         * 
         * @param value
         *            The value of 'listed_count'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setListedCount(long value) {
            validate(fields()[11], value);
            this.listed_count = value;
            fieldSetFlags()[11] = true;
            return this;
        }

        /**
         * Checks whether the 'listed_count' field has been set.
         * 
         * @return True if the 'listed_count' field has been set, false otherwise.
         */
        public boolean hasListedCount() {
            return fieldSetFlags()[11];
        }

        /**
         * Clears the value of the 'listed_count' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearListedCount() {
            fieldSetFlags()[11] = false;
            return this;
        }

        /**
         * Gets the value of the 'favourites_count' field.
         * 
         * @return The value.
         */
        public long getFavouritesCount() {
            return favourites_count;
        }

        /**
         * Sets the value of the 'favourites_count' field.
         * 
         * @param value
         *            The value of 'favourites_count'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setFavouritesCount(long value) {
            validate(fields()[12], value);
            this.favourites_count = value;
            fieldSetFlags()[12] = true;
            return this;
        }

        /**
         * Checks whether the 'favourites_count' field has been set.
         * 
         * @return True if the 'favourites_count' field has been set, false otherwise.
         */
        public boolean hasFavouritesCount() {
            return fieldSetFlags()[12];
        }

        /**
         * Clears the value of the 'favourites_count' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearFavouritesCount() {
            fieldSetFlags()[12] = false;
            return this;
        }

        /**
         * Gets the value of the 'statuses_count' field.
         * 
         * @return The value.
         */
        public long getStatusesCount() {
            return statuses_count;
        }

        /**
         * Sets the value of the 'statuses_count' field.
         * 
         * @param value
         *            The value of 'statuses_count'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setStatusesCount(long value) {
            validate(fields()[13], value);
            this.statuses_count = value;
            fieldSetFlags()[13] = true;
            return this;
        }

        /**
         * Checks whether the 'statuses_count' field has been set.
         * 
         * @return True if the 'statuses_count' field has been set, false otherwise.
         */
        public boolean hasStatusesCount() {
            return fieldSetFlags()[13];
        }

        /**
         * Clears the value of the 'statuses_count' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearStatusesCount() {
            fieldSetFlags()[13] = false;
            return this;
        }

        /**
         * Gets the value of the 'created_at' field.
         * 
         * @return The value.
         */
        public java.time.Instant getCreatedAt() {
            return created_at;
        }

        /**
         * Sets the value of the 'created_at' field.
         * 
         * @param value
         *            The value of 'created_at'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setCreatedAt(java.time.Instant value) {
            validate(fields()[14], value);
            this.created_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
            fieldSetFlags()[14] = true;
            return this;
        }

        /**
         * Checks whether the 'created_at' field has been set.
         * 
         * @return True if the 'created_at' field has been set, false otherwise.
         */
        public boolean hasCreatedAt() {
            return fieldSetFlags()[14];
        }

        /**
         * Clears the value of the 'created_at' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearCreatedAt() {
            fieldSetFlags()[14] = false;
            return this;
        }

        /**
         * Gets the value of the 'profile_image_url' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getProfileImageUrl() {
            return profile_image_url;
        }

        /**
         * Sets the value of the 'profile_image_url' field.
         * 
         * @param value
         *            The value of 'profile_image_url'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setProfileImageUrl(java.lang.CharSequence value) {
            validate(fields()[15], value);
            this.profile_image_url = value;
            fieldSetFlags()[15] = true;
            return this;
        }

        /**
         * Checks whether the 'profile_image_url' field has been set.
         * 
         * @return True if the 'profile_image_url' field has been set, false otherwise.
         */
        public boolean hasProfileImageUrl() {
            return fieldSetFlags()[15];
        }

        /**
         * Clears the value of the 'profile_image_url' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearProfileImageUrl() {
            profile_image_url = null;
            fieldSetFlags()[15] = false;
            return this;
        }

        /**
         * Gets the value of the 'profile_banner_url' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getProfileBannerUrl() {
            return profile_banner_url;
        }

        /**
         * Sets the value of the 'profile_banner_url' field.
         * 
         * @param value
         *            The value of 'profile_banner_url'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setProfileBannerUrl(java.lang.CharSequence value) {
            validate(fields()[16], value);
            this.profile_banner_url = value;
            fieldSetFlags()[16] = true;
            return this;
        }

        /**
         * Checks whether the 'profile_banner_url' field has been set.
         * 
         * @return True if the 'profile_banner_url' field has been set, false otherwise.
         */
        public boolean hasProfileBannerUrl() {
            return fieldSetFlags()[16];
        }

        /**
         * Clears the value of the 'profile_banner_url' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearProfileBannerUrl() {
            profile_banner_url = null;
            fieldSetFlags()[16] = false;
            return this;
        }

        /**
         * Gets the value of the 'profile_background_image_url' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getProfileBackgroundImageUrl() {
            return profile_background_image_url;
        }

        /**
         * Sets the value of the 'profile_background_image_url' field.
         * 
         * @param value
         *            The value of 'profile_background_image_url'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setProfileBackgroundImageUrl(java.lang.CharSequence value) {
            validate(fields()[17], value);
            this.profile_background_image_url = value;
            fieldSetFlags()[17] = true;
            return this;
        }

        /**
         * Checks whether the 'profile_background_image_url' field has been set.
         * 
         * @return True if the 'profile_background_image_url' field has been set, false otherwise.
         */
        public boolean hasProfileBackgroundImageUrl() {
            return fieldSetFlags()[17];
        }

        /**
         * Clears the value of the 'profile_background_image_url' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearProfileBackgroundImageUrl() {
            profile_background_image_url = null;
            fieldSetFlags()[17] = false;
            return this;
        }

        /**
         * Gets the value of the 'default_profile' field.
         * 
         * @return The value.
         */
        public boolean getDefaultProfile() {
            return default_profile;
        }

        /**
         * Sets the value of the 'default_profile' field.
         * 
         * @param value
         *            The value of 'default_profile'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setDefaultProfile(boolean value) {
            validate(fields()[18], value);
            this.default_profile = value;
            fieldSetFlags()[18] = true;
            return this;
        }

        /**
         * Checks whether the 'default_profile' field has been set.
         * 
         * @return True if the 'default_profile' field has been set, false otherwise.
         */
        public boolean hasDefaultProfile() {
            return fieldSetFlags()[18];
        }

        /**
         * Clears the value of the 'default_profile' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearDefaultProfile() {
            fieldSetFlags()[18] = false;
            return this;
        }

        /**
         * Gets the value of the 'default_profile_image' field.
         * 
         * @return The value.
         */
        public boolean getDefaultProfileImage() {
            return default_profile_image;
        }

        /**
         * Sets the value of the 'default_profile_image' field.
         * 
         * @param value
         *            The value of 'default_profile_image'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setDefaultProfileImage(boolean value) {
            validate(fields()[19], value);
            this.default_profile_image = value;
            fieldSetFlags()[19] = true;
            return this;
        }

        /**
         * Checks whether the 'default_profile_image' field has been set.
         * 
         * @return True if the 'default_profile_image' field has been set, false otherwise.
         */
        public boolean hasDefaultProfileImage() {
            return fieldSetFlags()[19];
        }

        /**
         * Clears the value of the 'default_profile_image' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearDefaultProfileImage() {
            fieldSetFlags()[19] = false;
            return this;
        }

        /**
         * Gets the value of the 'withheld_in_countries' field.
         * 
         * @return The value.
         */
        public java.util.List<java.lang.CharSequence> getWithheldInCountries() {
            return withheld_in_countries;
        }

        /**
         * Sets the value of the 'withheld_in_countries' field.
         * 
         * @param value
         *            The value of 'withheld_in_countries'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setWithheldInCountries(java.util.List<java.lang.CharSequence> value) {
            validate(fields()[20], value);
            this.withheld_in_countries = value;
            fieldSetFlags()[20] = true;
            return this;
        }

        /**
         * Checks whether the 'withheld_in_countries' field has been set.
         * 
         * @return True if the 'withheld_in_countries' field has been set, false otherwise.
         */
        public boolean hasWithheldInCountries() {
            return fieldSetFlags()[20];
        }

        /**
         * Clears the value of the 'withheld_in_countries' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearWithheldInCountries() {
            withheld_in_countries = null;
            fieldSetFlags()[20] = false;
            return this;
        }

        /**
         * Gets the value of the 'time_zone' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getTimeZone() {
            return time_zone;
        }

        /**
         * Sets the value of the 'time_zone' field.
         * 
         * @param value
         *            The value of 'time_zone'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setTimeZone(java.lang.CharSequence value) {
            validate(fields()[21], value);
            this.time_zone = value;
            fieldSetFlags()[21] = true;
            return this;
        }

        /**
         * Checks whether the 'time_zone' field has been set.
         * 
         * @return True if the 'time_zone' field has been set, false otherwise.
         */
        public boolean hasTimeZone() {
            return fieldSetFlags()[21];
        }

        /**
         * Clears the value of the 'time_zone' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearTimeZone() {
            time_zone = null;
            fieldSetFlags()[21] = false;
            return this;
        }

        /**
         * Gets the value of the 'lang' field.
         * 
         * @return The value.
         */
        public java.lang.CharSequence getLang() {
            return lang;
        }

        /**
         * Sets the value of the 'lang' field.
         * 
         * @param value
         *            The value of 'lang'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setLang(java.lang.CharSequence value) {
            validate(fields()[22], value);
            this.lang = value;
            fieldSetFlags()[22] = true;
            return this;
        }

        /**
         * Checks whether the 'lang' field has been set.
         * 
         * @return True if the 'lang' field has been set, false otherwise.
         */
        public boolean hasLang() {
            return fieldSetFlags()[22];
        }

        /**
         * Clears the value of the 'lang' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearLang() {
            lang = null;
            fieldSetFlags()[22] = false;
            return this;
        }

        /**
         * Gets the value of the 'geo_enabled' field.
         * 
         * @return The value.
         */
        public java.lang.Boolean getGeoEnabled() {
            return geo_enabled;
        }

        /**
         * Sets the value of the 'geo_enabled' field.
         * 
         * @param value
         *            The value of 'geo_enabled'.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder setGeoEnabled(java.lang.Boolean value) {
            validate(fields()[23], value);
            this.geo_enabled = value;
            fieldSetFlags()[23] = true;
            return this;
        }

        /**
         * Checks whether the 'geo_enabled' field has been set.
         * 
         * @return True if the 'geo_enabled' field has been set, false otherwise.
         */
        public boolean hasGeoEnabled() {
            return fieldSetFlags()[23];
        }

        /**
         * Clears the value of the 'geo_enabled' field.
         * 
         * @return This builder.
         */
        public lol.memory.ts.avro.User.Builder clearGeoEnabled() {
            geo_enabled = null;
            fieldSetFlags()[23] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public User build() {
            try {
                User record = new User();
                record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
                record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.time.Instant) defaultValue(fields()[1]);
                record.screen_name = fieldSetFlags()[2] ? this.screen_name
                        : (java.lang.CharSequence) defaultValue(fields()[2]);
                record.name = fieldSetFlags()[3] ? this.name : (java.lang.CharSequence) defaultValue(fields()[3]);
                record.location = fieldSetFlags()[4] ? this.location
                        : (java.lang.CharSequence) defaultValue(fields()[4]);
                record.url = fieldSetFlags()[5] ? this.url : (java.lang.CharSequence) defaultValue(fields()[5]);
                record.description = fieldSetFlags()[6] ? this.description
                        : (java.lang.CharSequence) defaultValue(fields()[6]);
                record.protected$ = fieldSetFlags()[7] ? this.protected$
                        : (java.lang.Boolean) defaultValue(fields()[7]);
                record.verified = fieldSetFlags()[8] ? this.verified : (java.lang.Boolean) defaultValue(fields()[8]);
                record.followers_count = fieldSetFlags()[9] ? this.followers_count
                        : (java.lang.Long) defaultValue(fields()[9]);
                record.friends_count = fieldSetFlags()[10] ? this.friends_count
                        : (java.lang.Long) defaultValue(fields()[10]);
                record.listed_count = fieldSetFlags()[11] ? this.listed_count
                        : (java.lang.Long) defaultValue(fields()[11]);
                record.favourites_count = fieldSetFlags()[12] ? this.favourites_count
                        : (java.lang.Long) defaultValue(fields()[12]);
                record.statuses_count = fieldSetFlags()[13] ? this.statuses_count
                        : (java.lang.Long) defaultValue(fields()[13]);
                record.created_at = fieldSetFlags()[14] ? this.created_at
                        : (java.time.Instant) defaultValue(fields()[14]);
                record.profile_image_url = fieldSetFlags()[15] ? this.profile_image_url
                        : (java.lang.CharSequence) defaultValue(fields()[15]);
                record.profile_banner_url = fieldSetFlags()[16] ? this.profile_banner_url
                        : (java.lang.CharSequence) defaultValue(fields()[16]);
                record.profile_background_image_url = fieldSetFlags()[17] ? this.profile_background_image_url
                        : (java.lang.CharSequence) defaultValue(fields()[17]);
                record.default_profile = fieldSetFlags()[18] ? this.default_profile
                        : (java.lang.Boolean) defaultValue(fields()[18]);
                record.default_profile_image = fieldSetFlags()[19] ? this.default_profile_image
                        : (java.lang.Boolean) defaultValue(fields()[19]);
                record.withheld_in_countries = fieldSetFlags()[20] ? this.withheld_in_countries
                        : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[20]);
                record.time_zone = fieldSetFlags()[21] ? this.time_zone
                        : (java.lang.CharSequence) defaultValue(fields()[21]);
                record.lang = fieldSetFlags()[22] ? this.lang : (java.lang.CharSequence) defaultValue(fields()[22]);
                record.geo_enabled = fieldSetFlags()[23] ? this.geo_enabled
                        : (java.lang.Boolean) defaultValue(fields()[23]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<User> WRITER$ = (org.apache.avro.io.DatumWriter<User>) MODEL$
            .createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<User> READER$ = (org.apache.avro.io.DatumReader<User>) MODEL$
            .createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

}
